"""Add created_at to Subs and Blacklist

Revision ID: 56da8fd86dfe
Revises: 5e2fd5815d23
Create Date: 2026-07-25 23:01:50.231012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56da8fd86dfe'
down_revision: Union[str, Sequence[str], None] = '5e2fd5815d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('subs', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subs', 'created_at')
    op.drop_column('blacklist', 'created_at')
    # ### end Alembic commands ###
