"""Create tables

Revision ID: 5e2fd5815d23
Revises:
Create Date: 2026-07-25 15:01:22.652881

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e2fd5815d23"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "servers",
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=True),
        sa.Column("member_count", sa.Integer(), nullable=True),
        sa.Column("quote", sa.Boolean(), nullable=False),
        sa.Column("prefix", sa.String(length=5), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("server_id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("is_anonymised", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "blacklist",
        sa.Column("blacklist_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column("by_owner", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.server_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("blacklist_id"),
        sa.UniqueConstraint("user_id", "server_id", "by_owner"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "gwenseek",
        sa.Column("seek_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column("user_message", sa.Text(), nullable=False),
        sa.Column("reasoning_content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.server_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("seek_id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "subs",
        sa.Column("sub_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.server_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("sub_id"),
        sa.UniqueConstraint("user_id", "server_id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "symbol_counter",
        sa.Column("symbol_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("latest_user", sa.BigInteger(), nullable=True),
        sa.Column("server_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.String(length=50), nullable=False),
        sa.Column("creating_user", sa.BigInteger(), nullable=False),
        sa.Column("setup_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creating_user"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["latest_user"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.server_id"],
        ),
        sa.PrimaryKeyConstraint("symbol_id"),
        sa.UniqueConstraint("channel_id"),
        sa.UniqueConstraint("server_id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "symbol_user",
        sa.Column("s_user_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("symbols_server", sa.BigInteger(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbols_server"],
            ["servers.server_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("s_user_id"),
        sa.UniqueConstraint("user_id", "symbols_server"),
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("symbol_user")
    op.drop_table("symbol_counter")
    op.drop_table("subs")
    op.drop_table("gwenseek")
    op.drop_table("blacklist")
    op.drop_table("users")
    op.drop_table("servers")
    # ### end Alembic commands ###
