"""MatchLog fixes and improvements

Revision ID: 702f8cc15096
Revises: ef309357bc3a
Create Date: 2026-08-13 19:23:35.850298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '702f8cc15096'
down_revision: Union[str, Sequence[str], None] = 'ef309357bc3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_log', sa.Column('player_cooldowns', sa.JSON(), nullable=False))
    op.add_column('match_log', sa.Column('enemy_cooldowns', sa.JSON(), nullable=False))
    op.alter_column('match_log', 'rng_seed',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('match_log', 'enemy_type',
               existing_type=mysql.INTEGER(),
               type_=sa.Enum('CASTER', 'MELEE', 'CANNON', 'CHAMP_BOSS', 'UBER_BOSS', name='enemytype'),
               existing_nullable=False)
    op.alter_column('match_log', 'gold_gained',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('match_log', 'xp_gained',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_log', 'xp_gained',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('match_log', 'gold_gained',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('match_log', 'enemy_type',
               existing_type=sa.Enum('CASTER', 'MELEE', 'CANNON', 'CHAMP_BOSS', 'UBER_BOSS', name='enemytype'),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('match_log', 'rng_seed',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('match_log', 'enemy_cooldowns')
    op.drop_column('match_log', 'player_cooldowns')
    # ### end Alembic commands ###
