"""Remove unique flag from channel_id, add strict field for pings

Revision ID: 77277aa87197
Revises: 56da8fd86dfe
Create Date: 2026-07-26 13:52:29.613288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77277aa87197'
down_revision: Union[str, Sequence[str], None] = '56da8fd86dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
