"""Add Last recount date

Revision ID: 888543833223
Revises: c9098063b48f
Create Date: 2026-08-02 14:14:44.216408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888543833223'
down_revision: Union[str, Sequence[str], None] = 'c9098063b48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbol_counter', sa.Column('last_recount', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbol_counter', 'last_recount')
    # ### end Alembic commands ###
