"""Add some necessary features to symbol counter.

Revision ID: 895b35af86db
Revises: 173417462b5f
Create Date: 2026-07-28 22:25:58.400830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '895b35af86db'
down_revision: Union[str, Sequence[str], None] = '173417462b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbol_counter', sa.Column('strict_channel', sa.BigInteger(), nullable=True))
    op.alter_column('symbol_counter', 'symbol',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('symbol_counter', 'symbol',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('symbol_counter', 'strict_channel')
    # ### end Alembic commands ###
