"""Add created at for ping users

Revision ID: aa909394aa92
Revises: 26908018ce4a
Create Date: 2026-08-10 10:59:18.105337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa909394aa92'
down_revision: Union[str, Sequence[str], None] = '26908018ce4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbol_ping_users', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbol_ping_users', 'created_at')
    # ### end Alembic commands ###
