"""stg

Revision ID: c470a039de9f
Revises: 9f8ced7406a2
Create Date: 2026-08-13 12:04:13.798033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c470a039de9f'
down_revision: Union[str, Sequence[str], None] = '9f8ced7406a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('gold', sa.BigInteger(), nullable=False),
    sa.Column('threads', sa.Integer(), nullable=False),
    sa.Column('cotton', sa.Integer(), nullable=False),
    sa.Column('elo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('player_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('gwen_state',
    sa.Column('gwen_state_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('fill_stacks', sa.Integer(), nullable=False),
    sa.Column('stitch_stacks', sa.Integer(), nullable=False),
    sa.Column('train_stacks', sa.Integer(), nullable=False),
    sa.Column('last_fill', sa.DateTime(), nullable=False),
    sa.Column('last_stitch', sa.DateTime(), nullable=False),
    sa.Column('last_train', sa.DateTime(), nullable=False),
    sa.Column('hp_current', sa.Float(), nullable=False),
    sa.Column('hp_max', sa.Float(), nullable=False),
    sa.Column('ad', sa.Float(), nullable=False),
    sa.Column('ap', sa.Float(), nullable=False),
    sa.Column('aspd', sa.Float(), nullable=False),
    sa.Column('armour', sa.Float(), nullable=False),
    sa.Column('mr', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('gwen_state_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('inventory',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('bonus_stats', sa.JSON(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('equipped', sa.Boolean(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('equipped_unequipped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('inventory_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('match_log',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('result', sa.Boolean(), nullable=False),
    sa.Column('enemy_id', sa.Integer(), nullable=False),
    sa.Column('enemy_type', sa.Integer(), nullable=False),
    sa.Column('gold_gained', sa.Integer(), nullable=True),
    sa.Column('xp_gained', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('match_id'),
    mysql_engine='InnoDB'
    )
    op.add_column('symbol_counter', sa.Column('strict', sa.Boolean(), nullable=False))
    op.drop_index(op.f('channel_id'), table_name='symbol_counter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('channel_id'), 'symbol_counter', ['channel_id'], unique=True)
    op.drop_column('symbol_counter', 'strict')
    op.drop_table('match_log')
    op.drop_table('inventory')
    op.drop_table('gwen_state')
    op.drop_table('players')
    # ### end Alembic commands ###
