"""Remove the actual foreign key reference

Revision ID: c9098063b48f
Revises: 6bb14730fb3b
Create Date: 2026-07-31 21:16:51.133723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9098063b48f'
down_revision: Union[str, Sequence[str], None] = '6bb14730fb3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blacklist_ibfk_2'), 'blacklist', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('blacklist_ibfk_2'), 'blacklist', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
