"""Add item ID column to InventoryItem

Revision ID: d9dd801c415f
Revises: c470a039de9f
Create Date: 2026-08-13 18:30:00.813868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9dd801c415f'
down_revision: Union[str, Sequence[str], None] = 'c470a039de9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('item_id', sa.Integer(), nullable=False))
    op.drop_column('match_log', 'config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_log', sa.Column('config', mysql.JSON(), nullable=False))
    op.drop_column('inventory', 'item_id')
    # ### end Alembic commands ###
