"""Add equipped inventory. Add inventory.

Revision ID: df3cb8769c9b
Revises: 702f8cc15096
Create Date: 2026-08-14 11:20:51.088370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'df3cb8769c9b'
down_revision: Union[str, Sequence[str], None] = '702f8cc15096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_item',
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('bonus_stats', sa.JSON(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.inventory_id'], ),
    sa.PrimaryKeyConstraint('inventory_item_id'),
    mysql_engine='InnoDB'
    )
    op.create_table('equipped_items',
    sa.Column('equipped_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('equipped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.inventory_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.inventory_item_id'], ),
    sa.PrimaryKeyConstraint('equipped_id'),
    sa.UniqueConstraint('inventory_id', 'slot', name='uq_equipped_inv_slot'),
    mysql_engine='InnoDB'
    )
    op.create_unique_constraint(None, 'gwen_state', ['player_id'])
    op.drop_column('gwen_state', 'aspd')
    op.add_column('inventory', sa.Column('grid_size_x', sa.Integer(), nullable=False))
    op.add_column('inventory', sa.Column('grid_size_y', sa.Integer(), nullable=False))
    op.add_column('inventory', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('inventory', sa.Column('modified_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'inventory', ['player_id'])
    op.drop_column('inventory', 'acquired_at')
    op.drop_column('inventory', 'equipped')
    op.drop_column('inventory', 'tier')
    op.drop_column('inventory', 'item_id')
    op.drop_column('inventory', 'bonus_stats')
    op.drop_column('inventory', 'equipped_unequipped_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('equipped_unequipped_at', mysql.DATETIME(), nullable=False))
    op.add_column('inventory', sa.Column('bonus_stats', mysql.JSON(), nullable=False))
    op.add_column('inventory', sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inventory', sa.Column('tier', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('inventory', sa.Column('equipped', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('inventory', sa.Column('acquired_at', mysql.DATETIME(), nullable=False))
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_column('inventory', 'modified_at')
    op.drop_column('inventory', 'created_at')
    op.drop_column('inventory', 'grid_size_y')
    op.drop_column('inventory', 'grid_size_x')
    op.add_column('gwen_state', sa.Column('aspd', mysql.FLOAT(), nullable=False))
    op.drop_constraint(None, 'gwen_state', type_='unique')
    op.drop_table('equipped_items')
    op.drop_table('inventory_item')
    # ### end Alembic commands ###
