"""Add version and rng seed to matchlog

Revision ID: ef309357bc3a
Revises: d9dd801c415f
Create Date: 2026-08-13 19:05:46.648794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef309357bc3a'
down_revision: Union[str, Sequence[str], None] = 'd9dd801c415f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_log', sa.Column('version', sa.String(length=32), nullable=False))
    op.add_column('match_log', sa.Column('rng_seed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_log', 'rng_seed')
    op.drop_column('match_log', 'version')
    # ### end Alembic commands ###
